#!/usr/bin/python
import sys
import os
from optparse import OptionParser
import cPickle as pickle


def look_at_asyncs(device_name, node_path='/srv/node/', num_results=5):
    async_path = os.path.join(node_path, device_name, 'async_pending')
    acc_dict = {}
    cont_dict = {}
    for async_suffix in os.listdir(async_path):
        for async_file in os.listdir(os.path.join(async_path, async_suffix)):
            try:
                async_file = os.path.join(async_path, async_suffix, async_file)
                file_data = pickle.load(open(async_file))
                acc = file_data['account']
                cont = file_data['container']
                if not (acc or cont):
                    print "Error: %s has invalid data" % async_file
                    continue
                if not acc in acc_dict:
                    acc_dict[acc] = {'num_asyncs': 0,
                                     'async_times': []}
                if (acc, cont) not in cont_dict:
                    cont_dict[(acc, cont)] = {'num_asyncs': 0,
                                              'async_times': []}
                acc_dict[acc]['num_asyncs'] += 1
                acc_dict[acc]['async_times'].append(
                    float(file_data['headers']['x-timestamp']))

                cont_dict[(acc, cont)]['num_asyncs'] += 1
                cont_dict[(acc, cont)]['async_times'].append(
                    float(file_data['headers']['x-timestamp']))
            except KeyError, e:
                print "KeyError: %s has invalid data. %s" % (async_file, e)
                continue

    acc_results = sorted(acc_dict.items(),
                         cmp=lambda a, b: cmp(b[1]['num_asyncs'],
                                              a[1]['num_asyncs']))
    cont_results = sorted(cont_dict.items(),
                          cmp=lambda a, b: cmp(b[1]['num_asyncs'],
                                               a[1]['num_asyncs']))

    print "\nRESULTS FOR %s" % device_name

    for name, result in [('Accounts', acc_results),
                         ('Account, Containers', cont_results)]:

        print '{0:^60}'.format('Top %s %s w/ asyncs' % (num_results, name)), \
              '{0:^6}'.format('#'), \
              '{0:^6}'.format('tDiff'), \
              '{0:^6}'.format('Freq')
        print '-' * 80

        for i in range(min(num_results, len(result))):
            min_time = min(result[i][1]['async_times'])
            max_time = max(result[i][1]['async_times'])
            num = int(result[i][1]['num_asyncs'])
            print '{0:^60}'.format(result[i][0]), \
                  '{0:^6}'.format(num), \
                  '{0:^6}'.format('%.2f' % (max_time - min_time)), \
                  '{0:^6}'.format('%.2f' % ((max_time - min_time) / num))

        print
        print

if __name__ == '__main__':
    parser = OptionParser(usage='''
Usage: async-tool [options] device-name [device-name]
Will look through a swift object-server's async-pendings and tell you about them.''')

    parser.add_option('-d', '--device-path', dest='device_path',
        default='/srv/node/',
        help='Path to directory container swift devices (default: /srv/node/)')
    parser.add_option('-n', '--num_results', dest='num_results',
        default='5',
        help='Number of results to return defaults to 5')

    args = sys.argv[1:]
    if not args:
        args.append('-h')
    options, args = parser.parse_args(args)

    if not args:
        parser.print_help()
        exit()
    for dev in args:
        look_at_asyncs(dev, options.device_path, int(options.num_results))
